### ISSUE TITLE
When viewing the TODO list:

### ISSUE THREAD

**Issue by andy-young** [mziccardi/2DoBox_Pivot#6]
- [x] Each TODO in the list should have a link or button to “Delete” (or 𝗫). 
- [x] Upon clicking “Delete”, the appropriate TODO should be removed from the list. 
- [x] The page should not reload when an idea is deleted.
- [x] The TODO should be removed from localStorage. It should not re-appear on next page load.

**Comment by andy-young** [comment]
All specs for this issue work with existing code, no changes made..
