### ISSUE TITLE
Editing an existing TODO

### ISSUE THREAD

**Issue by andy-young** [mziccardi/2DoBox_Pivot#7]
When a user clicks the title or task of a TODO in the list, that text should:  
- [x] Become an editable text field, pre-populated with the existing TODO title or task.
- [x] The user should be able to “commit” their changes by pressing “Enter/Return” or by clicking outside of the text field.
- [x] If the user reloads the page, their edits will be reflected.
